[tool.poetry]
name = "quantfreedom"
version = "0.2.0.0"
description = "I don't want to put a description here So I wont"
authors = ["Neo <quantfreedom1022@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = ">=1.26.1"
numba = ">=0.58.1"
ipykernel = ">=6.25.0"
dash = ">=2.9.1"
dash-bootstrap-templates = ">=1.1.1"
ipywidgets = ">=8.1.1"
jupyter-dash = ">=0.4.2"
notebook = ">=6.5.6"
pandas = ">=2.1.1"
plotly = ">=5.17.0"
tables = ">=3.9.2"
kaleido = [
{version="0.1.0.post1", markers="sys_platform != 'darwin'", source = "pypi"},
{version="0.2.1.post1", markers="sys_platform == 'darwin'", source = "pypi"},
]
python-benedict=">=0.33.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
mysql-connector-python = "8.3.0"
aws-cdk-lib = "2.133.0"
constructs = "10.0.0"
fastapi = ">=0.110.0"
mangum = ">=0.17.0"
httpx = ">=0.27.0"
cryptography = "42.0.5"
discord-py = {version = "2.3.2", extras = ["voice"]}
pyjwt = "2.8.0"
aiogram = "3.4.1"
email-validator = "2.1.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "1.5.3"
griffe = "0.38.0"
mkdocs-material = "9.4.14"
mkdocstrings = "0.24.0"
mkdocs-gen-files = "0.5.0"
mkdocs-open-in-new-tab = "1.0.3"

[tool.poetry.group.aws]
optional = true

[tool.poetry.group.aws.dependencies]
numpy = ">=1.26.1"
fastapi = ">=0.110.0"
mangum = ">=0.17.0"
httpx = ">=0.27.0"
mysql-connector-python = "8.3.0"
cryptography = ">=42.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"